### ISSUE TITLE
模型和地形同时存在取点

### ISSUE THREAD

**Issue by fdwszd123** [hongfaqiu/cesium-extends#10]
如果模型和地形同时存在画线等的时候应该是直接按照模型就取点了，可能有些点在模型上有些点在地形上，这种怎么处理呢

**Comment by hongfaqiu** [comment]
@fdwszd123 在模型上绘制时可以这样写：
此外可以升级@cesium-extends/drawer@1.3.2，修复了model模式下绘制线面地形上也会出现图形的问题
```ts
// 创建Drawer实例
const drawer = new Drawer(viewer, {
  model: true,
});

// 开始绘制
drawer.start({
  type: 'POLYGON',
  dynamicOptions: {
    classificationType: ClassificationType.CESIUM_3D_TILE
  },
  finalOptions: {
    classificationType: ClassificationType.CESIUM_3D_TILE
  }
});
```
参考资料https://cesium.com/learn/cesiumjs/ref-doc/PolylineGraphics.html#.ConstructorOptions

**Comment by HengLiYang** [comment]
@hongfaqiu 你好库主，我用的@cesium-extends/measure 1.1.4版本，然后它绘制的时候model: true,又出现上面提问者的这个问题了，就是地形和模型上同时存在这个绘制面积区域
