### ISSUE TITLE
请问测距时，打的Tip，在二维显示不出来。感觉是Tip高度不能设置，我的图层是高德地图

### ISSUE THREAD

**Issue by CendyceChen** [hongfaqiu/cesium-extends#15]

**Comment by CendyceChen** [comment]
找到解决办法了，要设置2D才会显示tip
      labelStyle:{
        heightReference: Cesium.HeightReference.NONE
      },

**Comment by hongfaqiu** [comment]
默认是HeightReference.CLAMP_TO_GROUND，readme都是GPT生成的，可能写得不太明白哈，ts声明中能找到没写全的部分
