### ISSUE TITLE
通过yarn 安装，使用小插件时候，提示安装缺少文件是什么原因呢？

### ISSUE THREAD

**Issue by liusihu-source** [hongfaqiu/cesium-extends#16]
安装@cesium-extends/zoom-control后，运行项目，提示如下缺少文件
node_modules/cesium/node_modules/autolinker/dist/es2015/index.js" points to missing source files
autolinker/dist/es2015/anchor-tag-builder.js" points to missing source files
node_modules/cesium/node_modules/autolinker/dist/es2015/html-tag.js" points to missing source files
等等

**Comment by liusihu-source** [comment]
![Uploading picture.png…]()

**Comment by hongfaqiu** [comment]
@liusihu-source 可能是安装依赖的时候出问题了吧，错误提示中的依赖项是cesium的，建议删除node_modules后重新安装

**Comment by liusihu-source** [comment]
@hongfaqiu 谢谢回复，昨天自己尝试解决了，因为自己也安装了vite-plugin-cesium依赖，经过测试，vite-plugin-cesium1.2.22版本不会出现如上报错信息，1.2.20会报错，估计新版本解决了这个bug。
