### ISSUE TITLE
Drawer模块，事件触发设计问题，双击和单击事件没有区分分离。

### ISSUE THREAD

**Issue by HappyFrontedCoding** [hongfaqiu/cesium-extends#23]
首先感谢作者的开源 ，在阅读作者Drawer模块Shape文件夹代码时，发现在Base里的DropPoint里有做两点之间距离判断，以防止两个相近点添加，在Polygon.js里发现playoff方法主动先cancel了一个点，然后我打点测试了一下发现首先move事件会动态pop或push进一个鼠标当前点，在左键droppoint时，此时SetBreakPoint里会push左键下的点，此时数组尾部会有两个相同点，当下次move事件触发时最后一个相同点又会被弹出push新的点。但是当双击左键结束绘制时，**因为没有做Cesium 原生Click和double click事件的分离**，也就不能分离click和double click。所以作者在base的droppoint方法里做了两点之间距离阈值限制，这是当双击事件触发的两次单击事件时保证最后一个droppoint不会添加进去，polygon里之所以在自定义的playoff里先做一次cancel是因为，作者在polygon的droppoint里没加上base的两点距离限制，所以在cancel处打点能看到多出2个点。**当我的START操作和End操作不为click和double_click时，这样就会有问题**。所以有个解决方法就是针对click和double_click这种会连带的事件进行区分，这也是Cesium的设计缺陷，要么干脆去掉自定义操作方式。

**Comment by hongfaqiu** [comment]
哈哈哈哈，好几年前写的代码了，我现在去看都晕乎乎的，逻辑有点多😂

**Comment by HappyFrontedCoding** [comment]
> 哈哈哈哈，好几年前写的代码了，我现在去看都晕乎乎的，逻辑有点多😂

haha，我也是好奇瞅瞅，但是后来想想能跑就行，就不管啦。我现在想想Cesium发展到现在有点重了，可能还是游戏引擎那套加上一些GIS支撑比如WMS、WMTS这种比较适合业务开发。我之前开发过用Three.js来做基础框架上面拓展GIS功能的，生态还挺全，希望未来能整个以WebGPU为Render的GIS引擎。
