### ISSUE TITLE
新版本@cesium-extends/drawer绘制矩形无法显示

### ISSUE THREAD

**Issue by annamithairil** [hongfaqiu/cesium-extends#25]
回调是能拿到实体的，但是地图上没有显示，包括圆形；点，线，多边形可以正常绘制。
https://extends.opendde.com/doc/drawer

**Comment by hongfaqiu** [comment]
应该是上次PR把这个改坏了 @HappyFrontedCoding

**Comment by hongfaqiu** [comment]
@annamithairil 修复了，圆形的半径绘制错误也一起修复了

**Comment by annamithairil** [comment]
> @annamithairil 修复了，圆形的半径绘制错误也一起修复了

非常感谢🙏
