### ISSUE TITLE
popup中wgs84ToWindowCoordinates在cesium新版本中已被废弃并删除

### ISSUE THREAD

**Issue by cugljd** [hongfaqiu/cesium-extends#27]
[cesium issues 12059](https://github.com/CesiumGS/cesium/issues/12059)

1.121版本后，`SceneTransforms.wgs84ToWindowCoordinates`已被删除，需要用`SceneTransforms.worldToWindowCoordinates`代替。

**Comment by hongfaqiu** [comment]
感谢，修复了
