### ISSUE TITLE
只能使用自带的么, 有对外方法调用么

### ISSUE THREAD

**Issue by JSMifans** [hongfaqiu/cesium-extends#5]

**Comment by hongfaqiu** [comment]
可以详细描述你的问题吗

**Comment by JSMifans** [comment]
比如 我现在用了 zoomController  自带有一个 工具样式,  如果我不想用自带的  用自己写的 click 调用zoomController 可以么, 我看zoomController 里面的方法都是私有的

**Comment by hongfaqiu** [comment]
复杂的用法可以拷贝代码到项目中改写哦

**Comment by JSMifans** [comment]
收到 感谢.  这个库 是没有提供 这种对方方法的是么

**Comment by hongfaqiu** [comment]
zoomController没有对外暴露方法，你可以拷贝类中的具体方法，粘贴到click函数中
