### ISSUE TITLE
在加载热力图时异常是什么原因造成的呢？

### ISSUE THREAD

**Issue by wanglingwen666** [hongfaqiu/cesium-extends#7]
![image](https://github.com/hongfaqiu/cesium-extends/assets/73384505/c73bc94b-431f-4aa9-95b2-160e5fd8f3ab)
![image](https://github.com/hongfaqiu/cesium-extends/assets/73384505/f9666d46-8d60-4334-a752-288e9ea0f9f4)

**Comment by hongfaqiu** [comment]
@cesium-extends/heat@1.0.3 已修复
