### ISSUE TITLE
文档挂了

### ISSUE THREAD

**Issue by s3xysteak** [hongfaqiu/cesium-extends#8]
没有discussion，只能发issue里了
没文档看用不了啦 : (

**Comment by hongfaqiu** [comment]
文档没挂呀[cesium-extends.pages.dev/](https://cesium-extends.pages.dev/)，你看看自己是不是代理或者网络环境出问题了😊

**Comment by hongfaqiu** [comment]
还没用过discussion，听你的，开了一个
